CREATE TABLE plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    common_name VARCHAR(120) NOT NULL,
    scientific_name VARCHAR(160) NOT NULL,
    image_url VARCHAR(400),
    indoor_friendly BOOLEAN NOT NULL,
    watering_recommendation VARCHAR(200) NOT NULL,
    light_recommendation VARCHAR(200) NOT NULL,
    ideal_climate VARCHAR(120),
    ideal_humidity VARCHAR(120),
    ideal_temperature VARCHAR(120),
    toxicidad VARCHAR(80),
    category VARCHAR(40) NOT NULL,
    light_requirement VARCHAR(10) NOT NULL,
    water_requirement VARCHAR(10) NOT NULL,
    humidity_requirement VARCHAR(10) NOT NULL
);