CREATE TABLE plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    common_name VARCHAR(120) NOT NULL,
    scientific_name VARCHAR(160) NOT NULL,
    image_url VARCHAR(400),
    indoor_friendly BOOLEAN NOT NULL,
    watering_recommendation VARCHAR(200) NOT NULL,
    light_recommendation VARCHAR(200) NOT NULL,
    ideal_climate VARCHAR(120),
    ideal_temperature VARCHAR(120),
    ideal_humidity VARCHAR(120),
    requerimientos_luz VARCHAR(200),
    frecuencia_riego VARCHAR(120),
    temperatura_ideal_min DECIMAL(4,1),
    temperatura_ideal_max DECIMAL(4,1),
    toxicidad VARCHAR(80)
);